config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :companies

resources :invoices do
  member do
    get 'export'
  end
end

resources :invoice_templates

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  unloadable

  include ActionView::Helpers::NumberHelper

  belongs_to :invoice_template
  has_one :contractor, :through => :contractor_id
  has_one :recipient, :through => :recipient_id

  has_many :invoice_rows, dependent: :destroy
  accepts_nested_attributes_for :invoice_rows, allow_destroy: true, reject_if: :all_blank

  def set_contractor(company)
    if company
      self.contractor_id = company.id
      self.contractor_name = company.name
      self.contractor_address = company.address
      self.contractor_director_name = company.director_name
      self.contractor_identifier = company.identifier
      self.contractor_vat_number = company.vat_number
      self.contractor_bank_name = company.bank_name
      self.contractor_bank_bic = company.bank_bic
      self.contractor_bank_iban = company.bank_iban
    end
  end

  def set_recipient(company)
    if company
      self.recipient_id = company.id
      self.recipient_name = company.name
      self.recipient_address = company.address
      self.recipient_director_name = company.director_name
      self.recipient_identifier = company.identifier
      self.recipient_vat_number = company.vat_number
      self.recipient_bank_name = company.bank_name
      self.recipient_bank_bic = company.bank_bic
      self.recipient_bank_iban = company.bank_iban
    end
  end

  TEMPLATE_VARS = {
    '[number]': :number,
    '[issue_date]': :issue_date,
    '[total_amount]': :total_amount,
    '[total_amount_words]': :total_amount_words,
    '[total_net_amount]': :total_net_amount,
    '[total_net_amount_words]': :total_net_amount_words,
    '[total_vat_amount]': :total_vat_amount,
    '[total_vat_amount_words]': :total_vat_amount_words,
    '[currency]': :currency,
    '[additional_currency]': :currency,
    '[contractor_name]': :contractor_name,
    '[contractor_address]': :contractor_address,
    '[contractor_director_name]': :contractor_director_name,
    '[contractor_identifier]': :contractor_identifier,
    '[contractor_vat_number]': :contractor_vat_number,
    '[contractor_bank_name]': :contractor_bank_name,
    '[contractor_bank_bic]': :contractor_bank_bic,
    '[contractor_bank_iban]': :contractor_bank_iban,
    '[recipient_name]': :recipient_name,
    '[recipient_address]': :recipient_address,
    '[recipient_director_name]': :recipient_director_name,
    '[recipient_identifier]': :recipient_identifier,
    '[recipient_vat_number]': :recipient_vat_number,
    '[recipient_bank_name]': :recipient_bank_name,
    '[recipient_bank_bic]': :recipient_bank_bic,
    '[recipient_bank_iban]': :recipient_bank_iban,
  }

  INVOICE_ROW_VARS = {
    '[invoice_row_1_title]': {index: 0, field_name: :title},
    '[invoice_row_1_amount]': {index: 0, field_name: :amount},
    '[invoice_row_1_amount_in_currency]': {index: 0, field_name: :amount_in_currency},
    '[invoice_row_1_quantity]': {index: 0, field_name: :quantity},
    '[invoice_row_1_amount_per_hour]': {index: 0, field_name: :amount_per_hour},

    '[invoice_row_2_title]': {index: 1, field_name: :title},
    '[invoice_row_2_amount]': {index: 1, field_name: :amount},
    '[invoice_row_2_amount_in_currency]': {index: 1, field_name: :amount_in_currency},
    '[invoice_row_2_quantity]': {index: 1, field_name: :quantity},
    '[invoice_row_2_amount_per_hour]': {index: 1, field_name: :amount_per_hour},

    '[invoice_row_3_title]': {index: 2, field_name: :title},
    '[invoice_row_3_amount]': {index: 2, field_name: :amount},
    '[invoice_row_3_amount_in_currency]': {index: 2, field_name: :amount_in_currency},
    '[invoice_row_3_quantity]': {index: 2, field_name: :quantity},
    '[invoice_row_3_amount_per_hour]': {index: 2, field_name: :amount_per_hour},

    '[invoice_row_4_title]': {index: 3, field_name: :title},
    '[invoice_row_4_amount]': {index: 3, field_name: :amount},
    '[invoice_row_4_amount_in_currency]': {index: 3, field_name: :amount_in_currency},
    '[invoice_row_4_quantity]': {index: 3, field_name: :quantity},
    '[invoice_row_4_amount_per_hour]': {index: 3, field_name: :amount_per_hour},
  }

  def render_template
    template = ''

    if self.invoice_template
      template = self.invoice_template.template

      TEMPLATE_VARS.each do |variable, field_name|
        template.gsub!(variable.to_s, format_field(self, field_name))
      end

      INVOICE_ROW_VARS.each do |variable, row_config|
        invoice_row = invoice_rows[row_config[:index]]
        if invoice_row
          template.gsub!(variable.to_s, format_field(invoice_row, row_config[:field_name]))
        end
      end
    end

    template
  end

  private

  def format_field(obj, field_name)
    field_type = obj.column_for_attribute(field_name.to_s).type

    if field_type == :date
      obj.send(field_name).strftime('%d.%m.%Y')
    elsif field_type == :decimal
      number_with_precision(obj.send(field_name), precision: 2).to_s
    else
      obj.send(field_name).to_s
    end
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  unloadable


  before_filter :find_project, :authorize
  before_filter :load_and_validate_invoice, only: [:edit, :update, :export, :destroy]

  def index
    @invoices = Invoice.where(project_id: @project.id).order(:number)
  end

  def new
    @invoice = Invoice.new
    @invoice.issue_date = Date.today
    @invoice.invoice_rows.build

    @companies = Company.where(project_id: @project.id).order(:name)
    @invoice_templates = InvoiceTemplate.where(project_id: @project.id).order(:name)
  end

  def create
    contractor_company = Company.find(params[:invoice][:contractor_id])
    recipient_company = Company.find(params[:invoice][:recipient_id])

    invoice = Invoice.new(invoice_params)
    invoice.project_id = @project.id
    invoice.set_contractor(contractor_company)
    invoice.set_recipient(recipient_company)
    invoice.save

    redirect_to invoices_url(project_id: @project.identifier)
  end

  def edit
    @companies = Company.where(project_id: @project.id).order(:name)
    @invoice_templates = InvoiceTemplate.where(project_id: @project.id).order(:name)
  end

  def update
    if @invoice.update(invoice_params)
      redirect_to invoices_url(project_id: @project.identifier)
    else
      render 'edit'
    end
  end

  def export
    respond_to do |format|
      format.pdf do
        pdf = WickedPdf.new.pdf_from_string(@invoice.render_template)
        filename = "invoice_#{@invoice.number}.pdf"
        send_data pdf, filename: filename, type: 'application/pdf'
      end
    end
  end

  def destroy
    @invoice.destroy!

    redirect_to invoices_url(project_id: @project.identifier)
  end

  private

  def find_project
    # @project variable must be set before calling the authorize filter
    @project = Project.find(params[:project_id])
  end

  def load_and_validate_invoice
    @invoice = Invoice.find(params[:id])

    if @invoice.project_id != @project.id
      redirect_to invoices_url(project_id: @project.identifier)
    end
  end

  def invoice_params
    params.require(:invoice).permit(
      :number, :issue_date, :total_amount, :total_amount_words,
      :total_net_amount, :total_net_amount_words,
      :total_vat_amount, :total_vat_amount_words, :currency,
      :additional_currency, :description, :invoice_template_id,
      invoice_rows_attributes: [:title, :amount, :amount_in_currency, :quantity, :amount_per_hour]
    )
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= error_messages_for 'invoice' %>

<div class="box tabular">
  <h2>Invoice</h2>

  <p>
    <label for="text">Number</label>
    <%= f.text_field :number %>
  </p>
  <p id="issue_date_area">
    <label for="issue_date">Issue date</label>
    <%= f.date_field(:issue_date, :size => 10, required: true) %>
    <%= calendar_for('issue_date') %>
  </p>
  <p>
    <label for="contractor_company_id">Contractor</label>
    <%= f.select :contractor_id, @companies.collect {|c| [c.name, c.id]}, include_blank: true %>
  </p>
  <p>
    <label for="recipient_company_id">Recipient</label>
    <%= f.select :recipient_id, @companies.collect {|c| [c.name, c.id]}, include_blank: true %>
  </p>
  <p>
    <label for="text">Total amount</label>
    <%= f.text_field :total_amount %>
  </p>
  <p>
    <label for="text">Total amount in words</label>
    <%= f.text_field :total_amount_words %>
  </p>
  <p>
    <label for="text">Total net amount</label>
    <%= f.text_field :total_net_amount %>
  </p>
  <p>
    <label for="text">Total net amount in words</label>
    <%= f.text_field :total_net_amount_words %>
  </p>
  <p>
    <label for="text">Total VAT amount</label>
    <%= f.text_field :total_vat_amount %>
  </p>
  <p>
    <label for="text">Total VAT amount in words</label>
    <%= f.text_field :total_vat_amount_words %>
  </p>
  <p>
    <label for="text">Currency</label>
    <%= f.text_field :currency %>
  </p>
  <p>
    <label for="text">Additional currency</label>
    <%= f.text_field :additional_currency %>
  </p>
  <p>
    <label for="text">Description</label>
    <%= f.text_field :description %>
  </p>
  <p>
    <label for="invoice_template_id">Template</label>
    <%= f.select :invoice_template_id, @invoice_templates.collect {|c| [c.name, c.id]}, include_blank: true %>
  </p>
</div>

  <% if not f.object.persisted? %>
    <div class="box tabular">
    <h2>Invoice rows</h2>

    <%= f.fields_for :invoice_rows do |ff| %>
      <p>
        <label for="title">Title</label>
        <%= ff.text_field :title %>
      </p>
      <p>
        <label for="amount">Amount</label>
        <%= ff.text_field :amount %>
      </p>
      <p>
        <label for="amount_in_currency">Amount in currency</label>
        <%= ff.text_field :amount_in_currency %>
      </p>
      <p>
        <label for="quantity">Quantity</label>
        <%= ff.text_field :quantity %>
      </p>
      <p>
        <label for="amount_per_hour">Amount per hour</label>
        <%= ff.text_field :amount_per_hour %>
      </p>

      <% if ff.object.persisted? %>
        <p>
          <label for="_destroy">Destroy</label>
          <%= ff.check_box :_destroy %>
        </p>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/invoices/_form_row.html.erb
<p>
  <label for="title">Title</label>
  <%= ff.text_field :title %>
</p>
<p>
  <label for="amount">Amount</label>
  <%= ff.text_field :amount %>
</p>
<p>
  <label for="amount_in_currency">Amount in currency</label>
  <%= ff.text_field :amount_in_currency %>
</p>
<p>
  <label for="quantity">Quantity</label>
  <%= ff.text_field :quantity %>
</p>
<p>
  <label for="amount_per_hour">Amount per hour</label>
  <%= ff.text_field :amount_per_hour %>
</p>

<% if ff.object.persisted? %>
  <p>
    <label for="_destroy">Destroy</label>
    <%= ff.check_box :_destroy %>
  </p>
<% end %>

app/views/invoices/edit.html.erb
<%= form_for @invoice, url: invoice_path(@invoice, project_id: @project.identifier) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag l(:button_save) %>
<% end %>

app/views/invoices/index.html.erb
<p>
  <%= link_to 'Companies', companies_path(project_id: @project.identifier) %>
</p>

<p>
  <%= link_to 'Invoice templates', invoice_templates_path(project_id: @project.identifier) %>
</p>

<p>
  <%= link_to 'New invoice', new_invoice_path(project_id: @project.identifier) %>
</p>


<div class="autoscroll">
  <table class="list issues">
    <thead>
      <tr>
        <th>Number</th>
        <th>Issue date</th>
        <th>Contractor</th>
        <th>Recipient</th>
        <th>Total amount</th>
        <th>Net amount</th>
        <th>VAT amount</th>
        <th>Currency</th>
        <th>Description</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @invoices.each do |invoice| %>
        <tr id="invoice-<%= invoice.id %>" class="hascontextmenu <%= cycle('odd', 'even') %>">
          <td><%= invoice.number %></td>
          <td><%= invoice.issue_date %></td>
          <td><%= invoice.contractor_name %></td>
          <td><%= invoice.recipient_name %></td>
          <td><%= invoice.total_amount %></td>
          <td><%= invoice.total_net_amount %></td>
          <td><%= invoice.total_vat_amount %></td>
          <td><%= invoice.currency %></td>
          <td><%= invoice.description %></td>
          <td>
            <%= link_to 'Edit', edit_invoice_path(invoice, project_id: @project.identifier) %>
            <br />
            <%= link_to 'Export', export_invoice_path(invoice, project_id: @project.identifier, format: :pdf) %>
          </td>
      </tr>
      <%end %>
    </tbody>
  </table>
</div>

app/views/invoices/new.html.erb
<%= form_for @invoice, url: invoices_path(project_id: @project.identifier) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag l(:button_save) %>
<% end %>