config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :companies

resources :invoices do
  member do
    get 'export'
  end
end

resources :invoice_templates

app/models/invoice_template.rb
class InvoiceTemplate < ActiveRecord::Base
  unloadable
end

app/controllers/invoice_templates_controller.rb
class InvoiceTemplatesController < ApplicationController
  unloadable


  before_filter :find_project, :authorize
  before_filter :load_and_validate_invoice_template, only: [:edit, :update, :destroy]

  def index
    @invoice_templates = InvoiceTemplate.where(project_id: @project.id)
  end

  def new
    @invoice_template = InvoiceTemplate.new
  end

  def create
    invoice_template = InvoiceTemplate.new(invoice_template_params)
    invoice_template.project_id = @project.id
    invoice_template.save

    redirect_to invoice_templates_url(project_id: @project.identifier)
  end

  def edit
  end

  def update
    if @invoice_template.update(invoice_template_params)
      redirect_to invoice_templates_url(project_id: @project.identifier)
    else
      render 'edit'
    end
  end

  def destroy
    @invoice_template.destroy!

    redirect_to invoice_templates_url(project_id: @project.identifier)
  end

  private

  def find_project
    # @project variable must be set before calling the authorize filter
    @project = Project.find(params[:project_id])
  end

  def load_and_validate_invoice_template
    @invoice_template = InvoiceTemplate.find(params[:id])

    if @invoice_template.project_id != @project.id
      redirect_to invoice_templates_url(project_id: @project.identifier)
    end
  end

  def invoice_template_params
    params.require(:invoice_template).permit(:name, :template)
  end

end

app/helpers/invoice_templates_helper.rb
module InvoiceTemplatesHelper
end

app/views/invoice_templates/_form.html.erb
<%= error_messages_for 'invoice' %>

<div class="box tabular">
  <p>
    <label for="text">Name</label>
    <%= f.text_field :name %>
  </p>
  <p>
    <label for="text">Template</label>
    <%= f.text_area :template, cols: 20, rows: 20 %>
  </p>
</div>

app/views/invoice_templates/_help.html.erb
<div class="box tabular">
  <h3>Predefined variables</h3>

  <table>
    <% Invoice::TEMPLATE_VARS.keys.each_slice(4) do |slice| %>
      <tr>
        <% slice.each do |variable| -%>
          <td><%= variable %></td>
        <% end -%>
      </tr>
    <% end %>

    <% Invoice::INVOICE_ROW_VARS.keys.each_slice(4) do |slice| %>
      <tr>
        <% slice.each do |variable| -%>
          <td><%= variable %></td>
        <% end -%>
      </tr>
    <% end %>
  </table>

</div>

app/views/invoice_templates/edit.html.erb
<%= render :partial => 'help' %>

<%= form_for @invoice_template, url: invoice_template_path(@invoice_template, project_id: @project.identifier) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag l(:button_save) %>
<% end %>

app/views/invoice_templates/index.html.erb
<p>
  <%= link_to 'Invoices', invoices_path(project_id: @project.identifier) %>
</p>

<p>
  <%= link_to 'New invoice template', new_invoice_template_path(project_id: @project.identifier) %>
</p>


<div class="autoscroll">
  <table class="list issues">
    <thead>
      <tr>
        <th>Name</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @invoice_templates.each do |invoice_template| %>
        <tr id="invoice-template-<%= invoice_template.id %>" class="hascontextmenu <%= cycle('odd', 'even') %>">
          <td><%= invoice_template.name %></td>
          <td>
            <%= link_to 'Edit', edit_invoice_template_path(invoice_template, project_id: @project.identifier) %>
          </td>
      </tr>
      <%end %>
    </tbody>
  </table>
</div>

app/views/invoice_templates/new.html.erb
<%= render :partial => 'help' %>

<%= form_for @invoice_template, url: invoice_templates_path(project_id: @project.identifier) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag l(:button_save) %>
<% end %>