config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :companies

resources :invoices do
  member do
    get 'export'
  end
end

resources :invoice_templates

app/models/company.rb
class Company < ActiveRecord::Base
  unloadable
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  unloadable


  before_filter :find_project, :authorize
  before_filter :load_and_validate_company, only: [:edit, :update, :destroy]

  def index
    @company = Company.new
    @companies = Company.where(project_id: @project.id).order(:name)
  end

  def create
    company = Company.new(company_params)
    company.project_id = @project.id
    company.save

    redirect_to companies_url(project_id: @project.identifier)
  end

  def edit
  end

  def update
    if @company.update(company_params)
      redirect_to companies_url(project_id: @project.identifier)
    else
      render 'edit'
    end
  end

  def destroy
    @company.destroy!

    redirect_to companies_url(project_id: @project.identifier)
  end

  private

  def find_project
    # @project variable must be set before calling the authorize filter
    @project = Project.find(params[:project_id])
  end

  def load_and_validate_company
    @company = Company.find(params[:id])

    if @company.project_id != @project.id
      redirect_to companies_url(project_id: @project.identifier)
    end
  end

  def company_params
    params.require(:company).permit(
      :name, :address, :director_name, :identifier,
      :vat_number, :bank_name, :bank_bic, :bank_iban
    )
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= error_messages_for 'company' %>

<div class="box tabular">
  <p>
    <label for="text">Name</label>
    <%= f.text_field :name %>
  </p>

  <p>
    <label for="text">Address</label>
    <%= f.text_field :address %>
  </p>
  <p>
    <label for="text">Director name</label>
    <%= f.text_field :director_name %>
  </p>
  <p>
    <label for="text">Identifier</label>
    <%= f.text_field :identifier %>
  </p>
  <p>
    <label for="text">VAT number</label>
    <%= f.text_field :vat_number %>
  </p>
  <p>
    <label for="text">Bank name</label>
    <%= f.text_field :bank_name %>
  </p>
  <p>
    <label for="text">Bank BIC</label>
    <%= f.text_field :bank_bic %>
  </p>
  <p>
    <label for="text">Bank IBAN</label>
    <%= f.text_field :bank_iban %>
  </p>

</div>

app/views/companies/edit.html.erb
<%= form_for @company, url: company_path(@company, project_id: @project.identifier) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag l(:button_save) %>
<% end %>

app/views/companies/index.html.erb
<p>
  <%= link_to 'Invoices', invoices_path(project_id: @project.identifier) %>
</p>

<div class="autoscroll">
  <table class="list issues">
    <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Director name</th>
        <th>Identifier</th>
        <th>VAT number</th>
        <th>Bank name</th>
        <th>Bank BIC</th>
        <th>Bank IBAN</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @companies.each do |company| %>
        <tr id="company-<%= company.id %>" class="hascontextmenu <%= cycle('odd', 'even') %>">
          <td><%= company.name %></td>
          <td><%= company.address %></td>
          <td><%= company.director_name %></td>
          <td><%= company.identifier %></td>
          <td><%= company.vat_number %></td>
          <td><%= company.bank_name %></td>
          <td><%= company.bank_bic %></td>
          <td><%= company.bank_iban %></td>
          <td><%= link_to 'Edit', edit_company_path(company, project_id: @project.identifier) %></td>
      </tr>
      <%end %>
    </tbody>
  </table>
</div>

<h2>Create new company</h2>

<%= form_for @company, url: companies_path(project_id: @project.identifier) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag l(:button_save) %>
<% end %>